


# Channel.create(:user_id => "0", :title => "가족을 지켜라", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "부탁해요, 엄마", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "용팔이", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "내 딸, 금사월", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "엄마", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "어머님은 내 며느리", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "다 잘될 거야", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "미세스 캅", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "이브의 사랑", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "돌아온 황금복", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "위대한 조강지처", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "딱 너 같은 딸", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "화정", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "애인있어요", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "그녀는 예뻤다", :mediatype => "drama")
# Channel.create(:user_id => "0", :title => "어셈블리", :mediatype => "drama")
# # 드라마 끝 예능 시작
# Channel.create(:user_id => "0", :title => "무한도전", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "해피선데이", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "일밤", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "정글의 법칙", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "가요무대", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "개그콘서트", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "이웃집 찰스", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "해피투게더", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "자기야", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "불후의 명곡", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "TV 동물농장", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "궁금한 이야기 Y", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "도전! 골든벨", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "1박2일", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "신기한TV", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "비정상회담", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "냉장고를 부탁해", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "썰전", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "마녀사냥", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "히든싱어", :mediatype => "entertainment")
# Channel.create(:user_id => "0", :title => "연예게 X파일", :mediatype => "entertainment")